[config]
default_to_workspace = false

[tasks.sqlx_prepare]
dependencies = ["install_sqlx_cli", "migrate_database"]
env = { DATABASE_URL = "postgres://postgres:password@localhost:5432/test" }
script = "sqlx prepare --merged"

[tasks.reinitialize_database]
dependencies = ["reset_database", "migrate_database"]

[tasks.reset_database]
dependencies = ["install_sqlx_cli"]
env = { DATABASE_URL = "postgres://postgres:password@localhost:5432/test" }
script = "sqlx database drop && sqlx database create"

[tasks.revert_database]
dependencies = ["install_sqlx_cli"]
env = { DATABASE_URL = "postgres://postgres:password@localhost:5432/test" }
script = "sqlx migrate revert"

[tasks.migrate_database]
dependencies = ["install_sqlx_cli"]
env = { DATABASE_URL = "postgres://postgres:password@localhost:5432/test" }
script = "sqlx migrate run"

[tasks.create_migration]
dependencies = ["install_sqlx_cli"]
env = { DATABASE_URL = "postgres://postgres:password@localhost:5432/test" }
command = "sqlx"
args = ["migrate", "add", "-r", "${@}"]

[tasks.install_sqlx_cli]
command = "cargo"
args = ["install", "sqlx-cli@0.6.3", "--no-default-features", "--features", "native-tls,postgres"]

[tasks.clippy]
env = { DATABASE_URL = "postgres://postgres:password@localhost:5432/test" }
command = "cargo"
args = ["clippy", "${@}"]

# build fee payer image
[tasks.build_server]
script = "docker build -f docker/ca_server.dockerfile -t ca_backend/ca_server ."

[tasks.simple_full_stack_up]
dependencies = ["build_server"]
script = "docker compose -f ca_server.yml -p ca_server up"

[tasks.simple_full_stack_down]
script = "docker compose -f ca_server.yml -p ca_server down"