[config]
default_to_workspace = false

[tasks.server]
script = "cargo run -r -p ca_server"

[tasks.upsert_articles]
script = "rm -rf cache/articles.bin && touch cache/articles.bin && chmod +x scripts/upsert_articles.sh && scripts/upsert_articles.sh"

[tasks.upsert_calibrations]
script = "rm -rf cache/calibrations.bin && touch cache/calibrations.bin && chmod +x scripts/upsert_calibrations.sh && scripts/upsert_calibrations.sh"

[tasks.upsert_testimonials]
script = "rm -rf cache/testimonials.bin && touch cache/testimonials.bin && chmod +x scripts/upsert_testimonials.sh && scripts/upsert_testimonials.sh"

[tasks.upsert_testimonial_images]
script = "rm -rf cache/testimonial_images.bin && touch cache/testimonial_images.bin && chmod +x scripts/upsert_testimonial_images.sh && scripts/upsert_testimonial_images.sh"

[tasks.upsert_category_images]
script = "rm -rf cache/category_images.bin && touch cache/category_images.bin && chmod +x scripts/upsert_category_images.sh && scripts/upsert_category_images.sh"

[tasks.upsert_content_type_images]
script = "rm -rf cache/content_type_images.bin && touch cache/content_type_images.bin && chmod +x scripts/upsert_content_type_images.sh && scripts/upsert_content_type_images.sh"

[tasks.reset_database]
dependencies = ["upsert_articles", "upsert_calibrations", "upsert_testimonials", "upsert_testimonial_images", "upsert_category_images", "upsert_content_type_images"]