[package]
name = "database"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
# external dependencies
anyhow = "1.0.40"
log = "0.4"
serde = { version = "^1.0", features = ["derive"] }
bincode = "1.3.3"
